### ISSUE TITLE
Move Staking Interface to Astral

### ISSUE THREAD

**Issue by dnoishi** [autonomys/astral#415]
##Context

This epic is to follow the task of moving staking interface to Astral

```[tasklist]
### Tasks
- [ ] https://github.com/subspace/astral/issues/416
- [ ] https://github.com/subspace/astral/issues/419
- [ ] https://github.com/subspace/astral/issues/417
- [ ] https://github.com/subspace/astral/issues/418
- [ ] https://github.com/subspace/astral/issues/454
- [ ] https://github.com/subspace/astral/issues/457
- [ ] https://github.com/subspace/astral/issues/460
- [ ] https://github.com/subspace/astral/issues/439
- [ ] https://github.com/subspace/astral/issues/420
- [ ] https://github.com/subspace/astral/issues/458
```

**Comment by DianaPertseva** [comment]
Moving it back to Backlog, since we have higher priority on Astral remaining bugs & issues and moving Staking into Astral @natachadelarosa @marc-aurele-besner

**Comment by marc-aurele-besner** [comment]
> Moving it back to Backlog, since we have higher priority on Astral remaining bugs & issues and moving Staking into Astral @natachadelarosa @marc-aurele-besner

This is the ticket for moving Staking into Astral

I thought this was the priority...

**Comment by DianaPertseva** [comment]
Sorry! Mixed this one up with Next.js task!
