### ISSUE TITLE
Update Astral to use new Squids APIs

### ISSUE THREAD

**Issue by dnoishi** [autonomys/astral#546]
## Update Astral to use new Squids APIs

```[tasklist]
### Bugs/issues
- [ ] Reward squid `operators` table is missing operators, every operator should be listed, not only the current one
- [ ] Rewards squids (and account?) should keep the total aggregate of all votes + block rewards for each account
```
```[tasklist]

### Tasks
- [ ] Verify that general, account, and rewards squid have all the needed tables, and all the logic is correct
- [ ] Verify that general (and account?) squids can be deployed for Nova
- [ ] Understand better the deployment flow of all these new squids, verify CI/CD workflows for these (staging and production)
- [ ] Add all these squids to status page
- [ ] Create better documentation on how to modify, maintain, and deploy these squids
- [ ] Change all references to old squid in Explorer for these new squids
- [ ] Remove old squids from the status page
- [ ] Add internal slack alert for these squids
```
