### ISSUE TITLE
Theme system for Explorer

### ISSUE THREAD

**Issue by marc-aurele-besner** [autonomys/astral#627]
## Theme system for Explorer

To make design and branding changes much easier, it will be great to improve the current theming setup in Astral, currently, we use hardcoded hex colors everywhere in tailwind className. This makes it painful to change the color scheme or add more flexibility.

As we will likely want to rebrand Astral Explorer, to be more in line with Autonomys brand color, these tasks will be great to accomplish this and make it easier for future-proofing the explorer.

```[tasklist]
### Tasks
- [ ] https://github.com/subspace/astral/issues/628
- [ ] https://github.com/subspace/astral/issues/629
- [ ] https://github.com/subspace/astral/issues/630
- [ ] https://github.com/subspace/astral/issues/631
```

**Comment by marc-aurele-besner** [comment]
A theme system is not something we are planning on implementing atm
