### ISSUE TITLE
Rebrand Astral to Autonomys

### ISSUE THREAD

**Issue by marc-aurele-besner** [autonomys/astral#630]
## Rebrand Astral to Autonomys

```[tasklist]
### Tasks
- [ ] https://github.com/subspace/astral/issues/658
- [ ] https://github.com/subspace/astral/issues/659
- [ ] https://github.com/subspace/astral/issues/660
- [ ] https://github.com/autonomys/astral/issues/1039
- [ ] https://github.com/autonomys/astral/issues/1040
```
