### ISSUE TITLE
Implement a staking squid

### ISSUE THREAD

**Issue by marc-aurele-besner** [autonomys/astral#731]
## Implement a staking squid

For the staking section purpose

```[tasklist]
### Tasks
- [ ] https://github.com/subspace/astral/issues/732
- [ ] https://github.com/subspace/astral/issues/734
- [ ] https://github.com/subspace/astral/issues/737
- [ ] https://github.com/subspace/astral/issues/738
- [ ] https://github.com/subspace/astral/issues/739
- [ ] https://github.com/subspace/astral/issues/761
- [ ] https://github.com/subspace/astral/issues/762
- [ ] https://github.com/subspace/astral/issues/763
```
